name: Continuous Integration

# Restrict CI to develop
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - "*"

jobs:
  # Build job
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        dotnetVersion: [ "3.1.101" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnetVersion }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
  # Generator job
  run-generator:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run generator
        run: dotnet run --project ./generator/generator.csproj --configuration Release